spring:
  application:
    name: voucher-admin
  data:
    mongodb:
      uri: mongodb://localhost:27017/voucherdb
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 8081

logging:
  level:
    com.voucher: DEBUG
