spring:
  application:
    name: voucher-user
  data:
    mongodb:
      uri: mongodb://localhost:27017/voucherdb
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8083
          jwk-set-uri: http://127.0.0.1:8083/jwks

server:
  port: 8082

logging:
  level:
    com.voucher: DEBUG
