spring:
  application:
    name: voucher-user
  data:
    mongodb:
      uri: mongodb://localhost:27017/voucherdb
    redis:
      host: localhost
      port: 6379

server:
  port: 8082

logging:
  level:
    com.voucher: DEBUG
